LifeCycle_Preview created
open-rmf/rmf_obstacle pull request #19
Opened 2024-03-17 14:31 UTC by Avisheet

# rmf_obstacle_detector_laserscan waiting to configure

While running  ros2 run rmf_obstacle_detector_laserscan laserscan_detector , I encountered *waiting to configure* .
The Lifecycle_preview provides a detailed description about how to configure and activate the node.

![WhatsApp Image 2024-03-16 at 4 58 31 PM](https://github.com/open-rmf/rmf_obstacle_detectors/assets/59338120/0b5c0abc-cfa4-428b-8ff8-155f01678fb2)

2024-03-17 14:57 UTC, Yadunund requested changes
Appreciate the effort to improve the documentation but there's no need to create a new markdown page summarizing lifecycle nodes. You may add a line to the existing readme that highlights that the nodes are lifecycle node and link to the lifecycle design document. Copy pasting text from existing documentation into a separate file here is not favorable practice.

It's best to add the commands to configure and activate the node right after the existing [command to run the node](https://github.com/open-rmf/rmf_obstacle_detectors#rmf_obstacle_detector_laserscan)

Also please rebase this PR with the latest `main` and ensure there are no unnecessary commits from other contributors.

2024-03-17 16:37 UTC, Avisheet commented
Thanks @Yadunund for reviewing and giving me suggestions . I was firstly thinking to provide a different markdown page for this with a brief description .
I will ensure to make the changes as suggested . Can you tell me should I add the picture of this "waiting to configure..." point or should I just add the commands .

2024-03-18 04:41 UTC, Yadunund commented
No need to include a screenshot.

2024-03-20 09:40 UTC, Yadunund requested changes
Please rebase your PR with `main` and ensure you don't include commits from other authors.

2024-03-20 09:40 UTC, Yadunund commented on README.md
> +The node is implemented as an[`rclcpp::lifecycle_node`](https://github.com/ros2/demos/tree/rolling/lifecycle) node where upon activation, it calibrates the surroundings based on the range values in t
```suggestion
The node is implemented as an [`rclcpp::lifecycle_node`](https://github.com/ros2/demos/tree/rolling/lifecycle) node where upon activation, it calibrates the surroundings based on the range values in the initial few `LaserScan` messages.
```

2024-04-02 01:19 UTC, Yadunund commented
@Avisheet do you still plan on addressing the comments in the PR?

2024-04-02 01:23 UTC, Avisheet commented
Yes @Yadunund . Due to some issues,  I wast able to focus here . But I ensure you that I will be working on this .

2024-04-02 02:25 UTC, Avisheet commented
Hey @Yadunund, I have rebased my PR with the main. I request you to review my PR and tell me the desired changes.

2024-04-02 02:59 UTC, Yadunund commented
The first commit still has changes from a different author.

2024-04-02 03:20 UTC, Avisheet commented
Hey @Yadunund, should I also remove commits 5,6 and 7?

2024-04-02 04:01 UTC, Avisheet commented
Hey @Yadunund , the last two commits appeard while resolving the merge errors after removing commits from other authors , can you once review it and tell me the desired changes I need to do now.

2024-04-02 04:16 UTC, Yadunund commented
Please resolve conflicts with main

2024-07-20 11:42 UTC, Yadunund approved these changes
Thanks for iterating and sorry for the delay in getting this merged.

2024-07-20 11:42 UTC, merged